name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: Win64
        - name: macOS
          os: macos-latest
          target: MacOS
        - name: Android32
          os: ubuntu-latest
          target: Android32
        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@825dce8c7404aacc975db01b09c99d295680cdec # v2.3.0 (Fixed SHA)
        with:
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: geode-sdk/build-geode-mod/combine@825dce8c7404aacc975db01b09c99d295680cdec
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: Build Output
          path: out
